import Link from "next/link";
import Image from "next/image";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Momentum",
  description: "Privacy policy for Momentum: Monthly Progress app. We don't collect any data.",
};

export default function Privacy() {
  return (
    <div className="min-h-screen bg-[#F5F5F0]">
      {/* Header */}
      <header className="container mx-auto px-6 py-6">
        <nav className="flex justify-between items-center">
          <Link href="/" className="flex items-center gap-3">
            <Image
              src="/app-icon.webp"
              alt="Momentum icon"
              width={40}
              height={40}
              className="rounded-[22%]"
            />
            <span className="text-2xl font-semibold text-black tracking-tight">Momentum</span>
          </Link>
          <div className="flex gap-6 text-sm">
            <Link href="/privacy" className="text-black font-medium">Privacy</Link>
            <Link href="/terms" className="text-gray-600 hover:text-black transition-colors">Terms</Link>
          </div>
        </nav>
      </header>

      <main className="container mx-auto px-6 py-16 max-w-3xl">
        <h1 className="text-4xl md:text-5xl font-bold text-black mb-4">Privacy Policy</h1>
        <p className="text-base text-gray-600 mb-12">Last updated: July 8, 2026</p>

        <div className="prose prose-lg max-w-none">
          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Our Commitment to Your Privacy</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              At Momentum, we take your privacy seriously. This Privacy Policy explains how we handle information in connection with the Momentum: Monthly Progress app.
            </p>
            <p className="text-sm text-black mb-4 leading-relaxed">
              <strong>The short version: We don&apos;t collect, store, or transmit any of your personal data.</strong>
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Information We Don&apos;t Collect</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              Momentum is designed to function entirely on your device. We do not collect, store, or transmit:
            </p>
            <ul className="list-disc pl-6 text-sm text-gray-600 space-y-2 mb-4">
              <li>Personal identification information</li>
              <li>Usage data or analytics</li>
              <li>Device information</li>
              <li>Location data</li>
              <li>Your daily check-in responses</li>
              <li>Any other data generated by your use of the app</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">How Your Data is Stored</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              All data created by Momentum, including your daily check-ins and monthly progress visualizations, is stored locally on your device. This data never leaves your device unless you choose to back it up through iCloud or other device backup mechanisms provided by Apple.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">No Account Required</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              Momentum does not require you to create an account, sign in, or provide any personal information to use the app. You can start using Momentum immediately after installation.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Third-Party Services</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              Momentum does not integrate with any third-party analytics, advertising, or tracking services. The app functions completely offline and does not communicate with any external servers.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">In-App Purchase</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              Momentum offers a one-time in-app purchase to unlock the full app functionality. This purchase is processed entirely through Apple&apos;s App Store. We do not have access to your payment information. Apple&apos;s privacy policy governs the collection and use of information related to in-app purchases.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Children&apos;s Privacy</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              Momentum is rated for ages 4+ and does not collect any personal information from users of any age. Parents can feel confident allowing their children to use Momentum.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Changes to This Privacy Policy</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-black mb-4">Contact Us</h2>
            <p className="text-base text-gray-700 mb-4 leading-relaxed">
              If you have any questions about this Privacy Policy, please contact us at:
            </p>
            <p className="text-sm text-gray-600 leading-relaxed">
              Bit Wise LLC<br />
              Email: support@momentum-app.com
            </p>
          </section>

          <section className="mb-12 bg-white rounded-2xl p-8 border border-gray-200">
            <h2 className="text-xl font-bold text-black mb-3">Privacy First Design</h2>
            <p className="text-base text-gray-700 leading-relaxed">
              Momentum was built from the ground up with privacy as a core principle. Your progress tracking data is yours alone, stored only on your device, and never shared with anyone.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <Link href="/" className="text-sm text-black hover:text-gray-600 transition-colors">
            ← Back to Home
          </Link>
        </div>
      </main>

      <footer className="container mx-auto px-6 py-16 mt-16">
        <div className="max-w-3xl mx-auto border-t border-gray-300 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-sm text-gray-600">
              <p className="font-semibold text-black mb-1">Momentum</p>
              <p>© 2026 Bit Wise LLC</p>
            </div>
            <div className="flex gap-6 text-sm text-gray-600">
              <Link href="/privacy" className="hover:text-black transition-colors">Privacy</Link>
              <Link href="/terms" className="hover:text-black transition-colors">Terms</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
